[package]
name = "jwt"
type = "lib"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]

[dependencies]
rsa = { tag = "v0.4.1", git = "https://github.com/noir-lang/noir_rsa/", directory = "lib" }
bignum = { tag = "v0.4.2", git = "https://github.com/noir-lang/noir-bignum" }
string_search = { tag = "v0.3.0", git = "https://github.com/noir-lang/noir_string_search/" }
nodash = { git = "https://github.com/olehmisar/nodash/", tag = "v0.39.2" }
