[package]
name = "jwt"
type = "lib"
authors = ["Oleh Misarosh <olehmisar@gmail.com>"]
compiler_version = ">=0.34.0"

[dependencies]
noir_rsa = { tag = "v0.3.1", git = "https://github.com/noir-lang/noir_rsa/", directory = "lib" }
string_search = { git = "https://github.com/noir-lang/noir_string_search/", tag = "v0.2.0" }
nodash = { git = "https://github.com/olehmisar/nodash/", tag = "v0.35.6" }
